### ISSUE TITLE
Couldnt progress, no bat form or power of mist

### ISSUE THREAD

**Issue by theWepen** [sotnrando/sotnrando#11]
This may be just the result of seed 1555258326352, but there didn't seem to be any way to get any flight/gravity boots by normal progression nor from wolf/mist glitching. I could not find the power of the mist, form of bat, or gravity boots in the first part of the castle even with that glitch. Is it possible that those items weren't placed where i could get early on without major glitches? I'd check this myself but it doesn't look like the spoiler log offers the relic locations, just starting equipment. Thanks!

**Comment by theWepen** [comment]
Note this is with a seed generated today at about 1pm or so

**Comment by 3snowp7im** [comment]
Soul of bat was in demon card location for this seed. You can see where relic locations are different from vanilla by using the randomizer from command line with the the `--check-vanilla` flag on the patched .bin file. I'll try to improve the output of the command line and possibly have an option to spoil relic locations on the web interface.

**Comment by theWepen** [comment]
My apologies. I had found nearly everything i could get without glitches but didn't realize i could make the double jump leap at the top of the waterfall, which would have unlocked the under-caverns where the Demon Card was. I apologize for my lack of skill and thank you for helping point me in the right direction on that one. Will remember that one in the future.
