### ISSUE TITLE
Logic change suggestions.

### ISSUE THREAD

**Issue by zaphod77** [sotnrando/sotnrando#110]
1) the Reverce Keep attic can be reached with only wolf+power of wolf+holy glasses. (or even no holy glasses at all if you do wolf richter skip)

however, you then need flight to escape.  So the two equip locations there should have escape logic set, because they can 100% be reached without the stuff to escape them.

2) wolf+thrust weapon is a valid and practical escape from lost mine if you don't have any other relics at all.   https://www.youtube.com/watch?v=RZ8QVchvjac

**Comment by 3snowp7im** [comment]
To which preset(s) logic are you requesting these changes?

**Comment by zaphod77** [comment]
number 2 should definitely be in speedrun and glitched, since the thrust sword logic is present there.  Shoudl probably NOT be in the normal non speedrun logic.

I would place wolf+power of wolf+holy glasses+flight for escape in normal logic, and wolf+power of wolf+flight for escape in speedrun and glitched presets, as richter skip is a speedrun trick. But if that seems too cruel, then it could be relegated to speedrun and higher.  Technically wolf+thurst sword should allow escape from reverce keep, but not even glitched will force a lengthy wolf rise on you, and i agree with that decision.

**Comment by eldri7ch2** [comment]
The logic has been revised several times for all of the presets by now. I'm closing this as resolved.
