### ISSUE TITLE
Possible logic error in Library Onyx speedrun preset.

### ISSUE THREAD

**Issue by zaphod77** [sotnrando/sotnrando#111]
If you somehow get to library onyx with only a thrust weapon (allowed by logic,) you can't actually escape without a cooperating enemy around, so it's very possible to softlock yourself in there.

pretty much ANY relic except wolf will let you out.

Wolf rise with thrust weapon should work as well.

**Comment by eldri7ch2** [comment]
Fixed in 3.16.1
