### ISSUE TITLE
Glitch Preset Softlocks

### ISSUE THREAD

**Issue by eldri7ch** [sotnrando/sotnrando#116]
The Sample and the Glitch Preset files both use "escapeRequirements" when the randomizer util.js is looking for "escapeRequires"

# Randomizer version:
3.15.0

Attached are the corrected files.

[glitch.json](https://github.com/3snowp7im/SotN-Randomizer/files/13245463/glitch.json)
[sample.json](https://github.com/3snowp7im/SotN-Randomizer/files/13245464/sample.json)

**Comment by eldri7ch2** [comment]
Fixed with the release of Glitch Remastered
