### ISSUE TITLE
Descriptions on website

### ISSUE THREAD

**Issue by OilFreak** [sotnrando/sotnrando#118]
Some of the options on the website could really use descriptions. Mainly _Turkey Mode_ and _Relic Locations_ (it's unclear if Relic Locations controls the randomization of relics, or toggles whether or not they're shuffled at all)

**Comment by 3snowp7im** [comment]
Turkey mode is purposefully not described and is meant for the player to figure out first hand.

> it's unclear if Relic Locations controls the randomization of relics, or toggles whether or not they're shuffled at all

Can you explain the difference between these? They sound like the same thing to me.

**Comment by OilFreak** [comment]
It's not clear (to me at least) if toggling Relic Locations controls the way that relics are randomized, or whether they're randomized at all.
Turkey mode is purposefully not described and is meant for the player to figure out first hand.

> Turkey mode is purposefully not described and is meant for the player to figure out first hand.

That's pretty funny, but in order for that joke to work the other options need descriptions. Even something as simple as "Music" should have a description. There's always going to be someone who doesn't understand something and you can't blame them for it.

**Comment by eldri7ch2** [comment]
Closing this as completed. New direction meant we changed / added new descriptions to things.
