### ISSUE TITLE
Twilight Cloak should require either form of mist + spikebreaker or form of mist+power of mist.

### ISSUE THREAD

**Issue by HateIsForLoosers** [sotnrando/sotnrando#122]
Hello, I used the adventure preset and locked on the twilight cloak check. The solution says that I should be fine, but I am not. 
Twilight Cloak should require either forn of mist + spikebreaker or form of mist+power of mist. But she solution requires only form of mist.
(I copied only the items that I am missing)
![SmartSelect_20240218_235626_Gallery](https://github.com/3snowp7im/SotN-Randomizer/assets/143417528/bb4d0079-7abe-4cc8-9416-f57d195b6aea)

**Comment by eldri7ch2** [comment]
Fixed in 3.16.1
