### ISSUE TITLE
Glitch Preset incorrectly assumes thrust wolf flight w Estoc

### ISSUE THREAD

**Issue by DoozyzooD69** [sotnrando/sotnrando#123]
# Seed Information
1708971887552 (tournament mode)

# Randomizer version:
3.15.0

# Spoilers:
N/A... basically I ran into a softlock with a seed that required me to get Form of Mist at Skill of Wolf using Estoc and Form of Wolf, which is not possible. The fix according to TLL is to not classify Estoc as a "Thrust Sword" in the .js file. Happy to provide further details

**Comment by TalicZealot** [comment]
Hardly a fix considering it would break other things. It would require the separate classification of normal thrust swords and Estoc. I think this was always known, but Glitch wasn't really worth the added complexity.

**Comment by DoozyzooD69** [comment]
FWIW, in TLL one solution presented was "Need to remove Estoc as a progression sword. In items.js, change this field to be false to avoid this issue"
![json](https://github.com/3snowp7im/SotN-Randomizer/assets/162381494/5c34bbb6-d691-4661-a4fe-329b540abe97)
Seeds have been generated with a downloadable randomizer with this change in code and from what I can tell it doesn't break anything

**Comment by eldri7ch2** [comment]
Fixed with the release of Glitch Remastered
