### ISSUE TITLE
Jewel of Open not found within first five relics

### ISSUE THREAD

**Issue by 03bgood** [sotnrando/sotnrando#13]
The first one (near the entrance) had the Gravity Boots

The one in Marble Gallery had one had the Bat Card

The one in the outer well elevator had Tooth of Vlad

The one in the library had the Eye of Vlad

The one I bought from the librarian was Power of Mist

What am I going to do, now!?

Nevermind, I can use the Gravity Boots to reach the room with the sub-weapon tanks.

**Comment by 3snowp7im** [comment]
There are many places you can check with gravity boots that early in the seed. Explore the castle. Or just check the "Show spoilers" option next time if you need help.
