### ISSUE TITLE
Filter doing nothing

### ISSUE THREAD

**Issue by fdelduque** [sotnrando/sotnrando#136]
In randomize_stats.js at line 103 there is a filter that never return true. Not sure if it's a bug or something left from previous versions and serve no purpose.

**Comment by eldri7ch2** [comment]
Please elaborate. What line number?

**Comment by eldri7ch2** [comment]
This is used at some point in the randomizer. I just debugged it.

![image](https://github.com/user-attachments/assets/638a7c89-b5d1-4092-a65d-d76667506397)
