### ISSUE TITLE
Bat relic not found in normal castle, impossible to progress!?

### ISSUE THREAD

**Issue by 03bgood** [sotnrando/sotnrando#14]
The part in the catacombs with the dark room filled with the spikes on the floor and ceiling is impossible to progress past, without the bat form and the silver and gold rings are impossible to obtain without either the bat form or the spike breaking armor and both rings are required to access the inverted castle.

Seed #: 1558087474104

**Comment by 3snowp7im** [comment]
please use the spoilers option before filing a bug. soul of bat is at sword cat, which you have access to with gravity boots, found at faerie scroll.

**Comment by 03bgood** [comment]
Theres no way to open the passageway in Royal Chapel to get to where the relic is. You can only open it, from the other side. Also cannot reach it from Orlox's Quarters. The Gravity Boots won't go up that high and the alcoves don't help, either. (in the room before the teleportal)
