### ISSUE TITLE
Path to bat relic, inacessble due to not having mist relics

### ISSUE THREAD

**Issue by 03bgood** [sotnrando/sotnrando#15]
Seed #: 1558087474104

The bat relic is found at Orlox's Quarter in a hidden sealed room above a bridge but I can't get to it and I don't have the mist and power of mist relics, either.

There's no way to open the passageway in Royal Chapel to get to where the relic is. You can only open it, from the other side. Also cannot reach it from Orlox's Quarters. The Gravity Boots won't go up that high and the alcoves don't help, either. (in the room before the teleportal)

**Comment by 3snowp7im** [comment]
again: show relic spoilers if youre having trouble before opening an issue.
go to faerie scroll location to get gravity boots.
go to bat card location to get leap stone.
go to sword card location to get soul of bat.
