### ISSUE TITLE
Request - Enemizer

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [sotnrando/sotnrando#17]
This tool is impressive but to make it really impressive enemies need to be shuffled.

**Comment by 3snowp7im** [comment]
thanks for your feedback. due to the way the game attaches sprites sheets on a per room basis, enemy randomization is not possible without a tremendous amount of work remapping the entire rom. as a result, this feature is likely not going to be on the roadmap anytime soon.

**Comment by halgorithm** [comment]
Is randomizing boss locations feasible at least, or still too much work to be worth it? You'd also probably have to scale their stats to match their new locations so runners won't accidentally walk into a certain death.
