### ISSUE TITLE
Request - Darkness mode - also known as 8x health and damage from enemies.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [sotnrando/sotnrando#18]
Yeah title says it all. As of right now the game just lacks punch. It is one of the sadest things about the game.

**Comment by 3snowp7im** [comment]
adding "punch" to the game is not a design goal of the randomizer. you may want to look into the hard type romhack for sotn and possibly create a new project based on that. that would be much closer to what youre looking for than a randomizer.

**Comment by P3rf3ctXZer0** [comment]
my request is based on alltp randomizer ... Sigh okay.
