### ISSUE TITLE
0 Exp Mode

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [sotnrando/sotnrando#19]
Essentially I want to have to rely on gear and wits. Alucard is just too badass for his own good.

**Comment by 3snowp7im** [comment]
this a bit related to your previous request for a dark mode, so ill just reiterate that the goal of the randomizer is to randomize, not to provide arbitrary difficulty sliders.

**Comment by halgorithm** [comment]
@P3rf3ctXZer0 You can accomplish a no-leveling conduct through cheats. Here's the gameshark code I used to disable leveling.

80097BE8 0062
80097BEC 0000
80097BEE 0000

Your level will show 98 for technical reasons, but your stats will be fixed to their initial values (familiars can still level up, though).
