### ISSUE TITLE
Insufficient Castle 2 Reqs?

### ISSUE THREAD

**Issue by EliteSoba** [sotnrando/sotnrando#2]
Current restrictions for castle 2 relics are:
```
(ctx.abilities.jewelOfOpen && ctx.abilities.mist
      && (ctx.abilities.bat || ctx.abilities.powerOfMist || gravityBootsChain)
      && (ctx.abilities.powerOfMist || ctx.abilities.sonar))
```
Which is mainly for getting Silver Ring, I believe.
If I understand correctly, sonar is used for putting Spike Breaker into logic, but doesn't check for having bat in the first place. I think this means you can end up with Jewel of Open, Mist, Gravity Boots, Leap Stone, and Echo of Bat, which isn't enough to get Silver Ring without a lot of shenanigans.

**Comment by 3snowp7im** [comment]
Should be fixed by https://github.com/3snowp7im/SotN-Relic-Randomizer/commit/910e8b8d6132f7c1f7aaea54828957f28d4f4f22
Please close if this resolves the issue.

**Comment by EliteSoba** [comment]
Yeah, looks good. Thanks!
