### ISSUE TITLE
no browser works for randomization. Firefox crashes. Tried every iso slus 00067 out there to see if different

### ISSUE THREAD

**Issue by ticklegrenade** [sotnrando/sotnrando#21]
no browser works for randomization. Firefox crashes and won't try to randomize. Tried every iso slus 00067 out there to see if different, but always just thinks and never completes. 

Also note that I won't use chrome, so is it tested only on chrome or something?

**Comment by 3snowp7im** [comment]
Please create a new issue using the bug report template:
https://github.com/3snowp7im/SotN-Randomizer/issues/new?assignees=3snowp7im&template=bug-report.md
