### ISSUE TITLE
Reviews from users.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [sotnrando/sotnrando#26]
https://youtu.be/5ImATxEZA64?t=525

**Comment by 3snowp7im** [comment]
This isn't reporting a bug, or even suggesting a feature. Instead, you've deeplink to a vod (not even *your* vod) of a streamer saying that the rando "needs work". I listened for a several minutes while he complained about *other* randomizers, never referencing what exactly "needs work" about this randomizer. What were you hoping to achieve by opening this ticket? This is essentially spam.

**Comment by P3rf3ctXZer0** [comment]
Its very bare with extremely wasted potential. Often the modes result in next to no challenge - why not look at some of the more popular randomizers? Why not take some inspiration. This tool legit does one thing - randomize. Which is great but it burns to know just how much wasted potential is in a project and beloved game as this.

**Comment by 3snowp7im** [comment]
What you consider "wasted potential" is actually separation of concerns. The randomizer is just that: a randomizer. It's not a general purpose romhacking tool. If other "randomizers" chose to be that, so be it, who am I to direct the efforts of those projects. However, I am not interested in turning this project into a swiss army knife. I have extensively discussed and planned *other* romhacking tools that would be compatible with this randomizer, but, as there are still in the early form of discussion and planning, there is no repo available for them currently. If you would like to absorb these future projects into your own "randomizer", nothing is stopping you from forking this project and implementing them yourself, or soliciting the work from others.
