### ISSUE TITLE
Feature request: Option to randomize boss rewards

### ISSUE THREAD

**Issue by halgorithm** [sotnrando/sotnrando#27]
Currently, there are many bosses that do nothing but serve to slow your progress along the path to a relic location, as well as some side bosses (mostly in the inverted castle) that are usually skipped entirely since they can never contain relics. An easy way to add some routing variety could be to allow every boss's reward to potentially be a relic. If possible, you could even go further with it and genericize the non-relic rewards to simply be any item instead of always Max Life Ups, which could lead to some interesting rewards (a powerful weapon, something useful like a library card, or something useless like a peanut).

**Comment by 3snowp7im** [comment]
Can't replace the non-relic boss rewards with relics without a lot of work. I disagree that the bosses exist only to slow you down. The developers' intent was to add challenge to the game and provide some needed experience points for leveling up. As for dropping an item from bosses, they would have to be a despawnable item, that is, an item that would be mostly inconsequential, like food or a damage dealing consumable item. At best, you might get a library card out of a boss drop. Doesn't really seem like it's worthwhile to implement at that point.

**Comment by halgorithm** [comment]
Sure, all bosses add some challenge and reward the player with experience. The problem I was pointing out was more that the set of bosses than can provide progression relics is currently static, which in turn means that others can generally be ignored if desired. For players who try to efficiently play through each seed, this effectively means the same bosses are always skipped since they can only contain random items, which is almost never worth spending time for since items are already plentiful.

That being said, I appreciate that it's a a difficult task that would involve a lot of work. I'm mainly bringing it up to point out features that could contribute toward a great rando experience for players.

**Comment by TonyTheTGR** [comment]
I would go further, and include all of the Life Max Ups and Heart Max Ups in the Relic Randomization List; to encourage the exploration of all corners of the castle in search of relics; and to much more greatly diversify path variation.

**Comment by TonyTheTGR** [comment]
Basically, if a relic can be placed at a vanilla relic point; then based on the logic to get to that point, it could also be placed at any Heart/Life Max Up (and therefore, bosses) accessible along that route with said abilities.

**Comment by TalicZealot** [comment]
That would break relic logic due to the fact that a lot of those locations are not easily reachable. It would require a customized ruleset.

**Comment by 3snowp7im** [comment]
I'm going to close this because I feel it is partly against the philosophy of the randomizer. Life vessels should be considered a powerup, not an item check.
