### ISSUE TITLE
Feature request: Open mode

### ISSUE THREAD

**Issue by halgorithm** [sotnrando/sotnrando#28]
An optional mode where all of the castle's shortcuts are unlocked and teleport rooms discovered by default, allowing you to go to most areas as soon as you want. Perhaps with an option to start the game with the Holy Glasses as well to give immediate access to the Inverted Castle.

**Comment by 3snowp7im** [comment]
While this would be fun, it has nothing to do with randomization. I realize that a lot of other "randomizers" inevitably turn into a swiss army knife of romhacking tools, but I'm trying to avoid that. I'll keep it in mind for future projects though.

**Comment by halgorithm** [comment]
I argue that an open mode actually fits well within the role of a randomization tool. If it existed, it would affect the relic placement algorithm since many locations that are normally gated behind access to certain relics would be accessible earlier. One example would be getting the Gravity Boots early on, then traveling to the inverted castle with Holy Glasses and finding many important progression relics that were placed in the inverted castle. Without having updated relic dependencies to reflect what is possible in an open mode, the placement randomization algorithm will always be limited to placing relics in the same limited number of spots, and could not utilize the open nature of the game if it were a completely decoupled separate project.
