### ISSUE TITLE
I can't make it work

### ISSUE THREAD

**Issue by kxbxnx** [sotnrando/sotnrando#29]
Well, my randomizer file have a 1KB (9KB) and have a "(undefined)" in the final, this is right?
If this is right how I can make it work?
I'm a dumb, sorry, someone help me please. 
:(

**Comment by 3snowp7im** [comment]
Closing issue because it does not adhere to any bug report template:
https://github.com/3snowp7im/SotN-Randomizer/issues/new/choose
