### ISSUE TITLE
Seed 1554245016613, Librarian has no Relic.

### ISSUE THREAD

**Issue by RetroNutcase** [sotnrando/sotnrando#3]
Other relics of note were

Cube of Zoe Location: Tooth of Vlad
Fairy Orb Location: Sword Familiar
Fairy Scroll Location: Vanilla item
Elevator in Outer Wall: Power of Mist

No way to proceed any further on this seed unless I'm missing something?

**Comment by 3snowp7im** [comment]
Can you retry this? I'm not sure when you created the seed, but the shop relic glitch should be fixed now.
