### ISSUE TITLE
I can't make it work, help me? ):

### ISSUE THREAD

**Issue by kxbxnx** [sotnrando/sotnrando#30]
my randomizer file have a 1KB (9KB) and have a "(undefined)" in the final, this is right?
If this is right how I can make it work?

**Comment by 3snowp7im** [comment]
3rd time I've asked you to fill out this template. Fill out all sections that apply to your issue. At least fill out the "How to reproduce" section or there is no way I can help.

# Seed URL
After randomizing, click the "Copy seed" button then paste here.

# Randomizer version:
Found in upper-right hand corner of web page.

# Operating system and version:

# Emulator and version:

# Bug description
Provide information relevant to the bug. The more information provided, the
easier it is to reproduce the bug.

# How to reproduce:
Open the Black Marble Gallery save on the attached virtual memory card and go
right, then...

**Comment by 3snowp7im** [comment]
Haven't received any response from you, so I assume you've figured out your issue. If not, please create a new issue.
