### ISSUE TITLE
Error page when trying to randomize

### ISSUE THREAD

**Issue by theodric30** [sotnrando/sotnrando#31]
Hi
Ive been using chrome while trying to randomize the game and after i drop the file and hit randomize an error page pops up and says "something went wrong while trying to display this page." Ive also tried using mozilla to see if it would work there instead of chrome and the thinking bar below the randomize button just keeps running for ever. 
![screen shot](https://user-images.githubusercontent.com/54642611/63884799-208d8880-c994-11e9-8acc-38655fefb08e.png)

**Comment by 3snowp7im** [comment]
Please complete the bug template:
https://github.com/3snowp7im/SotN-Randomizer/issues/new?assignees=3snowp7im&template=bug-report.md
