### ISSUE TITLE
Feature request: Music randomization

### ISSUE THREAD

**Issue by bdjeffyp** [sotnrando/sotnrando#32]
First off, great work you have done here with this randomizer. I'm enjoying this game again with a new set of challenges and it is thanks to this work!

I was wondering if zones could point to different music data? It'd be fun to have the randomizer mix up the tunes, just as a little fun% type mod to the game. Even better, have a flag that has most or all of the inverted castle music point back to it's original music (I'm looking at Final Toccata specifically... that song drove me crazy as I was exploring the inverted castle). 

This idea is something that would be an obvious low priority (hell, I'd do it myself if I knew where in the data the zones are pointing to the music data). However, having reviewed Nyxojaele's documentation of the data, it could be something that isn't possible if the music is contained within the zone's map data and we have to completely overwrite the preexisting information, making this more trouble that what it would be worth.

Anyway, just wanted to throw this idea out there. Thanks again for this fresh take on SotN!

**Comment by 3snowp7im** [comment]
Music randomizer is implemented in 2.10
