### ISSUE TITLE
No movement options

### ISSUE THREAD

**Issue by Soundmastermatt** [sotnrando/sotnrando#33]
Unless I'm mistaken I can not reach any movement (Double jump, super jump, or flight). After all "jewel of open done" left with only short form mist. Set on Agonize. 

# Seed URL
Castlevania
# Randomizer version:
1.7.27
# Spoilers:
  Soul of Bat at Power of Wolf (no flight)
  Fire of Bat at Echo of Bat
  Echo of Bat at Power of Mist
  Force of Echo at Gravity Boots
  Soul of Wolf at Merman Statue
  Power of Wolf at Spirit Orb
  Skill of Wolf at Soul of Wolf
  Form of Mist at Leap Stone
  Power of Mist at Soul of Bat (No double jump)
  Gas Cloud at Faerie Scroll
  Cube of Zoe at Ring of Vlad
  Spirit Orb at Ghost Card
  Gravity Boots at Eye of Vlad (Just not an option)
  Leap Stone at Demon Card (need flight to hit ape button)
  Holy Symbol at Faerie Card (need flight)
  Faerie Scroll at Skill of Wolf
  Jewel of Open at Jewel of Open
  Merman Statue at Gas Cloud
  Bat Card at Bat Card
  Ghost Card at Heart of Vlad
  Faerie Card at Sword Card
  Demon Card at Cube of Zoe
  Sword Card at Form of Mist
  Heart of Vlad at Holy Symbol
  Tooth of Vlad at Force of Echo
  Rib of Vlad at Tooth of Vlad
  Ring of Vlad at Fire of Bat
  Eye of Vlad at Rib of Vlad

**Comment by 3snowp7im** [comment]
Use soul of wolf + power of wolf to jump over the waterfall to get to the ape button, then get double jump at demon card.

**Comment by Soundmastermatt** [comment]
okay I'll wait for the next reply

**Comment by 3snowp7im** [comment]
I just told you what you need to do to progress. What are you hoping to get out of the next reply?
