### ISSUE TITLE
Is it working, over half is not moving (between 3 seeds)

### ISSUE THREAD

**Issue by Soundmastermatt** [sotnrando/sotnrando#34]
13 out of 28 between two seeds are in the same place. 15/28 the same between Castlevania (seed from soft lock report) and Randomizations. 14/28 the same between Castlevania and Wild Mouse. All movement is the same across all three. 

# Seed URL
seed 1 Randomizations
seed 2 Wild Mouse

# Randomizer version:
1.7.27

# Spoilers:
seed 1
  Soul of Bat at Power of Wolf (same)
  Fire of Bat at Bat Card
  Echo of Bat at Power of Mist (same)
  Force of Echo at Faerie Card
  Soul of Wolf at Merman Statue (same)
  Power of Wolf at Spirit Orb (same)
  Skill of Wolf at Echo of Bat 
  Form of Mist at Leap Stone (same)
  Power of Mist at Soul of Bat (same)
  Gas Cloud at Form of Mist
  Cube of Zoe at Ring of Vlad (same)
  Spirit Orb at Heart of Vlad
  Gravity Boots at Eye of Vlad (same)
  Leap Stone at Demon Card (same)
  Holy Symbol at Skill of Wolf 
  Faerie Scroll at Soul of Wolf 
  Jewel of Open at Jewel of Open (same)
  Merman Statue at Gas Cloud (same)
  Bat Card at Faerie Scroll 
  Ghost Card at Ghost Card (same)
  Faerie Card at Gravity Boots
  Demon Card at Cube of Zoe (same)
  Sword Card at Sword Card
  Heart of Vlad at Holy Symbol
  Tooth of Vlad at Rib of Vlad
  Rib of Vlad at Tooth of Vlad
  Ring of Vlad at Force of Echo
  Eye of Vlad at Fire of Bat
seed 2
  Soul of Bat at Power of Wolf (same)
  Fire of Bat at Soul of Wolf
  Echo of Bat at Power of Mist (same)
  Force of Echo at Form of Mist 
  Soul of Wolf at Merman Statue (same)
  Power of Wolf at Spirit Orb (same)
  Skill of Wolf at Skill of Wolf 
  Form of Mist at Leap Stone (same)
  Power of Mist at Soul of Bat (same)
  Gas Cloud at Gravity Boots
  Cube of Zoe at Ring of Vlad (same)
  Spirit Orb at Sword Card 
  Gravity Boots at Eye of Vlad (same)
  Leap Stone at Demon Card (same)
  Holy Symbol at Echo of Bat 
  Faerie Scroll at Heart of Vlad
  Jewel of Open at Jewel of Open (same)
  Merman Statue at Gas Cloud (same)
  Bat Card at Bat Card
  Ghost Card at Ghost Card (same)
  Faerie Card at Faerie Card
  Demon Card at Cube of Zoe (same)
  Sword Card at Faerie Scroll
  Heart of Vlad at Force of Echo
  Tooth of Vlad at Fire of Bat
  Rib of Vlad at Tooth of Vlad
  Ring of Vlad at Holy Symbol
  Eye of Vlad at Rib of Vlad

**Comment by Soundmastermatt** [comment]
seed 4: supercalifragilisticexpialidocious same problem. 12/28 with Randomizations. 14/28 with Wild Mouse.

**Comment by 3snowp7im** [comment]
Your previous report stated that you were using the Agonize preset. This preset is more of a plandomizer than a randomizer. As the description of the preset states, it designs the seed to maximize backtracking. In order to make this guarantee, many random factors in relic placement must be sacrificed. If you're seeking a truly random experience while still ensuring a softlock-free seed, please use the Safe preset.

**Comment by Soundmastermatt** [comment]
but I want to randomize and have alot of backtracking. That's why I choose agonize. Nowhere do the site say half of the relics will be locked in one spot. What is the point if all the good relics are not random.

**Comment by 3snowp7im** [comment]
Then play some safe seeds. You'll find plenty of seeds like that.
