### ISSUE TITLE
Candles dropping nothing?

### ISSUE THREAD

**Issue by theLavenderFlock** [sotnrando/sotnrando#36]
# Seed URL
578608952933 and 1578612631891

# Randomizer version:
1.7.27

# Operating system and version:
Windows 10 Education 1809

# Browser and version:
Opera GX core: 64.0.3417.150

# Emulator and version:
ePSXe v2.0.5

# Bug description
Candles after the Richter fight don't drop anything. I've gotten both of these files to past the first boss, and the randomization is working for the most part, but candles and fires don't drop hearts, sub items, money, etc. They drop nothing at all. 

# How to reproduce:
Attempt to get hearts or sub items etc from candles once you begin playing as Alucard. I'm not sure if this is an intended feature, but I saw in the changelogs a fix for candles not being randomized, so I assumed it is not.

**Comment by TalicZealot** [comment]
You need Cube of Zoe in order for candles to drop things.

**Comment by theLavenderFlock** [comment]
Holy cow I never knew this even after beating sotn vanilla. Thank you for the response.

Closing
