### ISSUE TITLE
Soul of Bat relic duplication Safe/Glitch modes

### ISSUE THREAD

**Issue by PaleDim** [sotnrando/sotnrando#37]
# Seed URL
1582825204182
Effects all seeds Safe or Glitch modes

# Randomizer version: 1.7.30

# Operating system and version: Windows 10 64 bit

# Browser and version: Chrome 80.0.3987.122

# Emulator and version: Bizhawk 2.3,  epsxe 2.02

# Bug description
By entering the location of Soul of Bat (library) from above will place Soul of Bat relic in the place of whatever relic is currently placed there by the randomizer. You could then move back to the mist gate and back to the relic location to obtain the intended relic placed there by the randomizer.  This will happen as long as you have not obtained Soul of Bat relic yet.

# How to reproduce:
By using 2x heart refresh and duplicator you can clip into the wall above and be able to land in the room. Use the following video to see where to start/stop the trick (the position of the last heart refresh is critical, note the small gap between Alucards back and the brown pillar. As the last heart refresh is going off be sure to hold left + jump to fall into the room)

[](https://www.youtube.com/watch?v=adid_oF4wRU&feature=emb_logo)

Alternatively you can input gameshark code listed below and press up+O to drop the floor out while standing on the floor above.
D0097490 1020
800730A8 0000
D0097490 4020
800730A8 0001

**Comment by 3snowp7im** [comment]
Are you sure this bug occurs in 1.7.30? I pushed an update last night that should fix this issue. I was able to verify just now using the seed you provided that the bat location relic is randomized when approaching through the mist gate and when clipping in from above via edge travel.

**Comment by PaleDim** [comment]
I was not aware the update. I had just come home for lunch and got your message off discord and just posted my info from yesterday into this post. I made a new seed tonight under 1.7.30 and this is fixed.
I used seed 1582863344357 and merman statue was there no matter which direction I entered in.

**Comment by 3snowp7im** [comment]
Glad to hear. Thanks for your help in reporting this issue, and hope you enjoy the randomizer.
