### ISSUE TITLE
Seed is Dropping Empty Hands

### ISSUE THREAD

**Issue by BrunoFelipeAlbuquerque** [sotnrando/sotnrando#38]
# Seed URL
1585775374676

# Randomizer version:
Safe

# Operating system and version:
Windows 7

# Emulator and version:
ePSX 3.0.5

# Bug description
The only items that drop are empty hands

# How to reproduce:
Start a new game, in the room with the merman on the bottom you will notice you will drop an empty hand, same with the ledge before death and both skeletons before the first save point.

**Comment by 3snowp7im** [comment]
Did you happen to notice today's date?
