### ISSUE TITLE
Seed 1593699828308 Incompletable?

### ISSUE THREAD

**Issue by fdelduque** [sotnrando/sotnrando#40]
# Seed URL
https://a.sotn.io/?26c,1593699828308

# Randomizer version:
2.9.22

# Spoilers:
Soul of Bat at Secret Boots
  Fire of Bat at Bat Card
  Echo of Bat at Jewel Sword
  Force of Echo at Gold Plate
  Soul of Wolf at Echo of Bat
  Power of Wolf at Tooth of Vlad
  Skill of Wolf at Sword of Hador
  Form of Mist at Reverse Caverns Diamond
  Power of Mist at Combat Knife
  Gas Cloud at Merman Statue
  Cube of Zoe at Platinum Mail
  Spirit Orb at Sunglasses
  Gravity Boots at Bandana
  Leap Stone at Bronze Cuirass
  Holy Symbol at Staurolite
  Faerie Scroll at Bastard Sword
  Jewel of Open at Ankh of Life
  Merman Statue at Caverns Onyx
  Bat Card at Lightning Mail
  Ghost Card at Morning Star
  Faerie Card at Badelaire
  Demon Card at Eye of Vlad
  Sword Card at Form of Mist
  Sprite Card at Dark Blade
  Nosedevil Card at Knight Shield
  Heart of Vlad at Walk Armor
  Tooth of Vlad at Leap Stone
  Rib of Vlad at Nunchaku
  Ring of Vlad at Cloth Cape
  Eye of Vlad at Blood Cloak
  Spike Breaker at Demon Card
  Gold Ring at Ring of Arcana
  Silver Ring at Gravity Boots
  Holy Glasses at Holy Symbol
Solutions:
  Holy Glasses < Merman Statue < Soul of Bat < Gravity Boots < Jewel of Open < Leap Stone
  Heart of Vlad < Jewel of Open < Leap Stone
  Tooth of Vlad < Leap Stone
  Rib of Vlad < Holy Symbol
                ^ Form of Mist < Holy Glasses < Merman Statue < Soul of Bat < Gravity Boots < Jewel of Open < Leap Stone
                ^ Power of Mist < Jewel of Open < Leap Stone
  Ring of Vlad
  Eye of Vlad < Leap Stone
Complexity: 9

Tried for like 1 hour getting the jewel of open(Ankh of Life) with only double jump and I just couldn't

**Comment by TalicZealot** [comment]
You should be able to reach all of the Jars in the big staircase room in Royal Chapel with just double jump. Make sure to hold jump to get as much height as possible.

**Comment by fdelduque** [comment]
I could get all jars except the jewel of open...

**Comment by 3snowp7im** [comment]
I tested every jar locatiom in the staircase room and all you need to reach them is leap stone. To clarify, "jar location" refers to the location of jars in the vanilla game. The fact that one of the jars got replaced by jewel of open does not change its accessibility via leap stone.
