### ISSUE TITLE
Wondering if you can make a "no cheese weapons" like crissaegrim setting

### ISSUE THREAD

**Issue by pervidefedback** [sotnrando/sotnrando#42]
No Crissaegrim, no Vorpal blade, no early Shield Rod/Alucard Shield combo.  No early Ring of Varda. Forgot to add no early duplicator.

That'd be fun, right?

**Comment by 3snowp7im** [comment]
The purpose of the randomizer is not to create completely subjective difficulty levels, but to randomize.
