### ISSUE TITLE
Feature request: Include a spoiler log with the randomized disc image

### ISSUE THREAD

**Issue by SenseiLeRoof** [sotnrando/sotnrando#44]
It's as easy as packing them in a ZIP file. Having to re-randomize just to find out if we might be softlocked is ridiculous.

**Comment by 3snowp7im** [comment]
It's as easy as copy and pasting the spoiler log from the text box before playing your seed. The current relic logic avoids all softlock scenarios, so if you're concerned you might need a bit of guidance to get through your seed, plan accordingly and check Show spoilers at generation time.
