### ISSUE TITLE
Feature request: Actual progress

### ISSUE THREAD

**Issue by SenseiLeRoof** [sotnrando/sotnrando#45]
The squeezy blue line doesn't help me know what the randomizer is doing or how long I can expect to wait, or if the app is quietly hanging behind the scenes and wasting time. Even a "Shuffling items, equipment and relics" with a percent indicator would help.

**Comment by 3snowp7im** [comment]
There is no way to tell how long it will take, it's entirely up to chance. 99.999% of the generation time is finding a relic placement strategy that meets the desired complexity without causing a softlock, so providing other status updates would be pointless.
