### ISSUE TITLE
Feature request: Tournament mode

### ISSUE THREAD

**Issue by TalicZealot** [sotnrando/sotnrando#48]
Multiple top runners have expressed the desire to have a way to disable spoilers for relic locations and solutions for competitive events.
Could be done with dedicated presets like "tournament safe", "tournament speedrun" or a separate subdomain, which would roll a different seed than the standard presets and disable spoilers.

**Comment by 3snowp7im** [comment]
Tournament mode is added in 2.15.0

It is implemented as a randomization option, so it in is included in the RNG seed. Consequently, the same seed produces different randomizations when tournament mode is enabled, however, spoiler verbosity above level 1 will be disabled in the CLI and browser.

I have also added the following convenience URLs:

t.sotn.io: Safe Tournament Mode
a.t.sotn.io: Adventure Tournament Mode
c.t.sotn.io: Casual Tournament Mode
s.t.sotn.io: Speedrun Tournament Mode
g.t.sotn.io: Glitch Tournament Mode
sc.t.sotn.io: Scavenger Tournament Mode
eh.t.sotn.io: Empty Hand Tournament Mode
