### ISSUE TITLE
Feature Request: Mystery Mode

### ISSUE THREAD

**Issue by CrystalGamerAG** [sotnrando/sotnrando#49]
Just an Idea.  It would be kind of cool to have a mystery setting for seed generation, so you don't know what kind of logic you have until you do some exploring.  Maybe not everyone would be into it, and maybe it wouldn't be applicable to this game, but I think it could be pretty cool!

**Comment by 3snowp7im** [comment]
Please create a new ticket for the second item. I'm not entirely clear what the request is, but I would prefer to discuss it in its own thread and not combine suggestions in a single issue.

**Comment by CrystalGamerAG** [comment]
my apologies, should be sorted now!

**Comment by eldri7ch2** [comment]
This is something we have on the back-burner. Stay tuned.

**Comment by eldri7ch2** [comment]
Closing this since we are already working on something like it.
