### ISSUE TITLE
Feature Request: weighted item pooling

### ISSUE THREAD

**Issue by CrystalGamerAG** [sotnrando/sotnrando#50]
Sorry about not having this in its own thread.  

The second request was if it would be possible to reduce item counts by replacing them with the empty hand item (like in the empty handed seeds).  If you could do this with a choice on what items are replaced you could create seeds with some items removed, or reduced in count and change the variance of the randomizer a significant amount.

**Comment by 3snowp7im** [comment]
I don't intend to implement a weighted item pool, but in the 3.x releases, you can use the `blockItems` and `blockDrops` features in your preset JSON to remove whatever you like from the game.
