### ISSUE TITLE
Feature Request: Boss shuffle (kind of)

### ISSUE THREAD

**Issue by CrystalGamerAG** [sotnrando/sotnrando#51]
I originally was going to leave this as a comment on the map shuffle inquiry, but figured it was different enough to warrant it's own ticket as it could be a lighter version of the map shuffle, shuffling only boss rooms.

Would it be possible to replicate a boss shuffle by remapping what doors lead where?   Like if you were to replace the left entrance to doppelganger 10 with the left entrance to medusa, and after the fight the right entrances to medusa would exit to the right of doppelganger 10.  This way only two bosses wouldn't be shuffled, dracula/shaft and richter.  The only thing I don't know how to manage exactly is the slogra and gaibon/beelzebub boss room as there are three entrances.  So idk exactly how that would work if you were to only shuffle boss rooms.  One solution, but I'm guessing that this would create a lot of errors with memory management (I say this with very limited knowledge of memory management).  You could potentially put all bosses in the slogra and gaibon or beelzebub boss room in order to do a boss shuffle.  Then you could map the upper entrance that would would need flight for to be the same as the lower entrance on the same side.

**Comment by 3snowp7im** [comment]
As with most games, and indeed as with every enemy in sotn, bosses are hardcoded to the room they appear in, so it very unlikely that bosses will be moved to new rooms.

The issue with boss rooms that have different geometries is that the third exit leads to rooms that can potentially hold relics. Addressing that issue gracefully would be very difficult, especially if it involved introducing load zones.

The biggest issue to me is the practicality. Without adding my own subjective boss ranking or difficulty scaling, it's very likely that a randomized boss order leads to an unbeatable seed. Imagine beezlebub being your first boss for instance. I have avoided subjectivity in the randomizer so far and I intend to keep it that way.

**Comment by eldri7ch2** [comment]
It is impossible, as SOTN is currently coded, to add a boss randomizer. Apologies.
