### ISSUE TITLE
Softlock at holy glasses check

### ISSUE THREAD

**Issue by MrRazzio** [sotnrando/sotnrando#52]
# Seed URL
https://t.sotn.io/?JuniorFinding16

# Randomizer version:
2.16.6

# Spoilers:
Cannot generate spoilers due to this being a tournament mode seed.

Gold/silver rings were at cube and spirit orb.  Holy glasses did not have flight.

**Comment by 3snowp7im** [comment]
This was a 2.16.5 seed, but the issue has been fixed in 2.16.6
