### ISSUE TITLE
Feature request: Random starting location

### ISSUE THREAD

**Issue by halgorithm** [sotnrando/sotnrando#53]
Option to have Alucard start in a random save room instead of at the castle entrance, perhaps by providing a save file to load. This would require updating each location's accessibility requirements based on each starting location.

**Comment by eldri7ch2** [comment]
There is already a tool that does this. I will talk with the developer about it to see if he wants to disclose how we can incorporate this into the Randomizer.

**Comment by TalicZealot** [comment]
This was included in one of the original open presets. If those files exist anywhere it would be in them.

**Comment by eldri7ch2** [comment]
Nice, will look around.

**Comment by eldri7ch2** [comment]
Added in 3.16.2
