### ISSUE TITLE
dev.sotn.io Safe Preset Failed

### ISSUE THREAD

**Issue by chrisaegrimm** [sotnrando/sotnrando#54]
# Seed URL
https://dev.sotn.io/?p:safe,n,7cc,DownToGetClowned

# Randomizer version:
3.1.0-2

# Operating system and version:
Windows 10 Home
Version 20H2

# Browser and version:
Google Chrome
Version 89.0.4389.82 (Official Build) (64-bit)

# Emulator and version:
BizHawk
v2.6.1 x64

# Bug description
A safe seed (tournament) was generated using the developmental build to create a PPF patch for a four-person race. The seed was not completable by Safe logic, and various other issues occurred. Here were the issues:

- On the file select, instead of saying the seed name, it showed vanilla text at the top (TalicZealot's Autotracker shows "Input RICHTER to play as Richter Belmont).

- The spoilers show different starting equipment than what you start with.

- All items found (not items dropped) were from a VERY limited pool consisting mostly of Shurikens and Green Tea.

- All items in the shop were the same within their type (all items were the same, all swords were the same, etc.). The one-time items in the shop were still functioning as intended, including the progression item.

- Holy Glasses were nowhere to be found, even after using Richter skip with bat to explore the 2nd Castle. Three out of four players had performed all checks and were unable to find them. All other progression items seemed present, including all five Vlad relics.

All seeds were generated from a PPF file I generated. I double-checked and created a second PPF with the same settings, which yielded identical results.

# How to reproduce:
Download the seed yourself using dev.sotn.io, selecting Safe Tournament (or using the provided link), and proceeding through the game.

**Comment by 3snowp7im** [comment]
Thanks for these reports. These should all be fixed in version 3.1.0 which is live on main. In the future, please create individual issues for each bug instead of consolidating them in one. This makes it easier to track the progress for each issue individualy and that way things don't fall through the cracks.
