### ISSUE TITLE
Incompletable Adventure Seed

### ISSUE THREAD

**Issue by thesatellite54** [sotnrando/sotnrando#55]
# Seed URL
https://a.sotn.io/?a36,culexplz

# Randomizer version:
3.0.26

# Spoilers:
  Soul of Bat at Echo of Bat
  Fire of Bat at Knight shield
  Echo of Bat at Talisman
  Force of Echo at Ring of Ares
  Soul of Wolf at Holy glasses
  Power of Wolf at Royal cloak
  Skill of Wolf at Goggles
  Form of Mist at Beryl circlet
  Power of Mist at Ankh of Life
  Gas Cloud at Trio
  Cube of Zoe at Icebrand
  Spirit Orb at Walk armor
  Gravity Boots at Shield Rod
  Leap Stone at Form of Mist
  Holy Symbol at Holy Symbol
  Faerie Scroll at Demon Card
  Jewel of Open at Sunstone
  Merman Statue at Leap Stone
  Bat Card at Sunglasses
  Ghost Card at Spike Breaker
  Faerie Card at Fire of Bat
  Demon Card at Reverse Caverns Garnet
  Sword Card at Mormegil
  Sprite Card at Gladius
  Nosedevil Card at Gold plate
  Heart of Vlad at Sword of Hador
  Tooth of Vlad at Gram
  Rib of Vlad at Mystic pendant
  Ring of Vlad at Alucard mail
  Eye of Vlad at Twilight cloak
  Spike Breaker at Fury plate
  Onyx at Cloth cape
  Zircon at Alucart sword
  Cat-eye circl. at Blood cloak

**Comment by 3snowp7im** [comment]
I think this is due to a typo causing Shield rod location to be a 0-relic check. Should be fixed in 3.0.27.
