### ISSUE TITLE
OG preset faulty logic

### ISSUE THREAD

**Issue by asdheyb** [sotnrando/sotnrando#56]
Bat being at Tooth means we can't normally get to spikebreaker following safe logic so the seed is "uncompletable".

# Seed URL
https://sotn.io/?p:og,59f,boomer%20seed

# Randomizer version:
3.2.0

# Spoilers:
Relic locations:
  Soul of Bat at Tooth of Vlad
  Fire of Bat at Ring of Vlad
  Echo of Bat at Sword Card
  Force of Echo at Heart of Vlad
  Soul of Wolf at Gravity Boots
  Power of Wolf at Power of Mist
  Skill of Wolf at Skill of Wolf
  Form of Mist at Leap Stone
  Power of Mist at Echo of Bat
  Gas Cloud at Bat Card
  Cube of Zoe at Form of Mist
  Spirit Orb at Ghost Card
  Gravity Boots at Demon Card
  Leap Stone at Spirit Orb
  Holy Symbol at Eye of Vlad
  Faerie Scroll at Holy Symbol
  Jewel of Open at Soul of Bat
  Merman Statue at Rib of Vlad
  Bat Card at Soul of Wolf
  Ghost Card at Jewel of Open
  Faerie Card at Gas Cloud
  Demon Card at Force of Echo
  Sword Card at Fire of Bat
  Heart of Vlad at Merman Statue
  Tooth of Vlad at Faerie Scroll
  Rib of Vlad at Cube of Zoe
  Ring of Vlad at Power of Wolf
  Eye of Vlad at Faerie Card
  Spike Breaker at Spike Breaker
  Gold ring at Gold ring
  Silver ring at Silver ring
  Holy glasses at Holy glasses

**Comment by 3snowp7im** [comment]
Should be fixed in 3.2.1
