### ISSUE TITLE
OG uncompletable seed 

### ISSUE THREAD

**Issue by asdheyb** [sotnrando/sotnrando#57]
JoO is in 2nd castle

# Seed URL
https://sotn.io/?p:og,beb,hm...

# Randomizer version:
3.2.0

# Spoilers:
Relic locations:
  Soul of Bat at Spirit Orb
  Fire of Bat at Soul of Wolf
  Echo of Bat at Heart of Vlad
  Force of Echo at Jewel of Open
  Soul of Wolf at Sword Card
  Power of Wolf at Merman Statue
  Skill of Wolf at Force of Echo
  Form of Mist at Cube of Zoe
  Power of Mist at Faerie Scroll
  Gas Cloud at Ghost Card
  Cube of Zoe at Bat Card
  Spirit Orb at Power of Mist
  Gravity Boots at Power of Wolf
  Leap Stone at Tooth of Vlad
  Holy Symbol at Echo of Bat
  Faerie Scroll at Gas Cloud
  Jewel of Open at Rib of Vlad
  Merman Statue at Gravity Boots
  Bat Card at Demon Card
  Ghost Card at Faerie Card
  Faerie Card at Leap Stone
  Demon Card at Eye of Vlad
  Sword Card at Fire of Bat
  Heart of Vlad at Holy Symbol
  Tooth of Vlad at Form of Mist
  Rib of Vlad at Ring of Vlad
  Ring of Vlad at Skill of Wolf
  Eye of Vlad at Soul of Bat
  Spike Breaker at Spike Breaker
  Gold ring at Gold ring
  Silver ring at Silver ring
  Holy glasses at Holy glasses

**Comment by 3snowp7im** [comment]
Should be fixed in 3.2.1
