### ISSUE TITLE
Candle drops 

### ISSUE THREAD

**Issue by asdheyb** [sotnrando/sotnrando#58]
This would count as a "minor" bug in every other preset except for Adventure, where it will cause softlocks due to not being able to access the Alucart room.

# Seed URL
Pretty much any seed in the last 4-5 days

# Randomizer version:
Found in upper-right hand corner of web page.

# Operating system and version:
W10 Pro 64

# Browser and version:
Chrome 89.0.4389.82 (Build oficial) (64 bits)

# Emulator and version:
BizHawk 2.6.1

# Bug description
Candles drop nothing but small hearts. This means no big hearts, money drops, sub-weapons, etc. This doesn't seem to affect the two Uncurse candles in the Library, which still drop use items.

# How to reproduce:
After getting Cube of Zoe, all candles will drop small hearts.

**Comment by 3snowp7im** [comment]
Should be fixed in 3.2.6
