### ISSUE TITLE
Bandanna not locked by Jewel of Open?

### ISSUE THREAD

**Issue by nikovaan** [sotnrando/sotnrando#59]
# Seed URL
https://sotn.io/?deibr:10:HATRNI:x:equipment:B:ML-MV-MB-MP:f:B-VL-MP:E:B-VLM-VLW-MP:e:HB-HVL-HMP:p:B-VL-MP:s:V-B-MP:M:L-V-B-MP:P:B-VL-MP:c:HB-HVL-HMP:V:B-VL-MP:L:J-L-V-B-MP:y:JU:U:J:b:V-B-MP:g:B-VL-MP:a:V-B-MP:d:JL-JB-JMP-JWp+B-L-V-MP:w:B-VL-MP:A:HB-HVL-HMP:T:HB-HVL-HMP:R:HB-HVLM-HVLW-HMP:N:HB-HVL-HMP:I:HB-HVL-HMP:K:JBE:G:JB-JVL-JMP:S:JKM:H:SG+B-VL-MP:Crystalcloak:J:Mormegil:JL-JB-JMP-JWp+B-L-V-MP:DarkBlade:HB-HVL-HMP:RingofArcana:HB-HVL-HMP:Holymail:B-VL-MP:Trio:HB-HVL-HMP:Jewelsword:WB:Mysticpendant:B-L-V-MP:AnkhofLife:B-L-V-MP:Morningstar:B-L-V-MP:Goggles:J-B-L-V-MP:Silverplate:J-B-L-V-MP:Cutlass:J-B-L-V-MP:Platinummail:B-V-MP:Falchion:B-L-V-MP:Goldplate:B-L-V-MP:Bekatowa:B-V-MP:Holyrod:B-V-MP:LibraryOnyx:B-L-V-MP:Alucartsword:zB-zL-zV-zMP:Broadsword:B-L-V-MP:Estoc:B-VL-MP:OlroxGarnet:B-VL-MP:Bloodcloak:B-L-V-MP:Shieldrod:B-L-V-MP:Knightshield:B-L-V-MP:Nunchaku:Jy:Knuckleduster:J:CavernsOnyx:JB-JyL-JMP:Secretboots:JB-JVL-JMP:Combatknife:JB-JL-JMP-JWp+B-L-V-MP:RingofAres:JdB-JdL-JdMP-JdWp-JnB-JnL-JnMP-JnWp+B-L-V-MP:Bloodstone:JB-JL-JMP-JWp+B-L-V-MP:Icebrand:JB-JL-JMP-JWp+B-L-V-MP:Walkarmor:JB-JL-JMP-JWp+B-L-V-MP:Berylcirclet:HBW:Talisman:HB-HVL-HMP:Katana:HB-HVL-HMP:Goddessshield:HB-HVL-HMP:Twilightcloak:HMB-HMVL-HMP:Talwar:HB-HVL-HMP:SwordofDawn:HB-HVL-HMP:Bastardsword:HB-HVL-HMP:Royalcloak:HB-HVL-HMP:Lightningmail:HB-HVL-HMP:Moonrod:HB-HVL-HMP:Sunstone:HB-HVL-HMP:Luminus:HB-HVL-HMP:Dragonhelm:HB-HVL-HMP:Shotel:HMB-HMVL-HMP:Staurolite:HMB-HMVL-HMP:Badelaire:HB-HVL-HMP:ForbiddenLibraryOpal:HB-HVL-HMP:ReverseCavernsDiamond:HB-HVL-HMP:ReverseCavernsOpal:HB-HVL-HMP:ReverseCavernsGarnet:HB-HVL-HMP:Osafunekatana:HB-HVL-HMP:Alucardshield:HB-HVL-HMP:Alucardsword:HB-HVL-HMP:NecklaceofJ:HB-HVL-HMP:FloatingCatacombsDiamond:HB-HVL-HMP:SwordofHador:HB-HVL-HMP:Alucardmail:HB-HVL-HMP:Gram:HB-HVL-HMP:Furyplate:HB-HVL-HMP,smk,3dd,IfOnlyKircheisWasHere

# Randomizer version:
3.4.0

# Operating system and version:
Windows 7  version 6.1, build 7601, service pack 1

# Browser and version:
Chrome 89.0.4389.90

# Emulator and version:
Bizhawk 2.4.2 x64

# Bug description
Jewel of Open was at Fairy Card, Gravity Boots was at Bandanna. Logic showed using Gravity Boots to obtain Jewel of Open, which is impossible. Seed was ultimately winnable by using a thrust sword to chain divekicks off of books to obtain Jewel of Open.

# How to reproduce:
Nothing special needed to reproduce.

**Comment by 3snowp7im** [comment]
This has been fixed in one of the recent releases.
