### ISSUE TITLE
Boss Drop Relic did not spawn

### ISSUE THREAD

**Issue by FacetRaccoon** [sotnrando/sotnrando#6]
Seed: Facet

So, the topic basically describes it.  As I was sweeping over inverted castle, one of the boss kills (Medusa apparently) just gave me nothing at all, no relic, no life up, etc.  I didn't remember exactly which 5 gave relics because I only know the game as a 100% sweep rather than paring down to only necessary checks for success, but anyway.

I was confused by that, but didn't think anything of it, til I had "as close to 200% map as you can get without being able to access Drac" as possible, and still had no 5th vlad relic.  At the time that happened, I thought one of the relics just wasn't in the seed or something.  As a last ditch effort I revisited the boss rooms, because I remembered one of them didn't drop anything when they should have dropped a relic, and lo and behold, the rib was sitting there in Medusa's room.

(Full disclosure: I am not actually sure that it was Medusa that gave no drop, and don't rule out that a boss kill somewhere else caused a relic to spawn in her room.  Sorry that I don't completely recall, but I'm just putting that possibility out there, though it does strike me as potentially outlandish.  Troubleshooting, nothing too weird to be a possibility, etc.)

I don't know if that's a normal thing that can happen, and I don't know if Olrox just deciding not to stop exploding and let me leave his room, softlocking me is normal either.  But those were two things that happened that I've never seen happen before, which may or may not be symptomatic of something in the randomizer, so I just thought I'd report these anomalies.  It didn't technically end up unwinnable, but I thought it was for a while, and can't say I know what's up with the rib just not spawning til the room was revisited (if that is what happened.)

**Comment by 3snowp7im** [comment]
Haven't been able to replicate this yet. If you're able to get a save game before medusa and can reliably replicate this behavior, it would really help me fix this. Haven't had reports of the Olrox explosion bug, but that seems to be a separate issue. Going to close issue for now, but please reopen if you're able to attach a .mcr with a save that can replicate the meduse glitch.

**Comment by 3snowp7im** [comment]
Also, if you open a new issue, please include which emulator was used.
