### ISSUE TITLE
Did I find a softlock?

### ISSUE THREAD

**Issue by VirtualEstatePlanner** [sotnrando/sotnrando#62]
# Seed Information
https://sotn.io/?12b,1618262658587

# Randomizer version:
3.5.6 Safe

# Spoilers:
Seed: 1618262658587
Starting equipment:
  Morningstar
  Medusa shield
  Steel helm
  Cloth tunic
  Blood cloak
  Turquoise
Relic locations:
  Soul of Bat at Silver ring
  Fire of Bat at Cube of Zoe
  Echo of Bat at Fire of Bat
  Force of Echo at Eye of Vlad
  Soul of Wolf at Crystal cloak
  Power of Wolf at Spirit Orb
  Skill of Wolf at Soul of Bat
  Form of Mist at Gas Cloud
  Power of Mist at Demon Card
  Gas Cloud at Dark Blade
  Cube of Zoe at Merman Statue
  Spirit Orb at Trio
  Gravity Boots at Soul of Wolf
  Leap Stone at Mormegil
  Holy Symbol at Ring of Arcana
  Faerie Scroll at Echo of Bat
  Jewel of Open at Form of Mist
  Merman Statue at Power of Mist
  Bat Card at Leap Stone
  Ghost Card at Ghost Card
  Faerie Card at Skill of Wolf
  Demon Card at Ring of Vlad
  Sword Card at Jewel of Open
  Sprite Card at Tooth of Vlad
  Nosedevil Card at Force of Echo
  Heart of Vlad at Holy glasses
  Tooth of Vlad at Heart of Vlad
  Rib of Vlad at Rib of Vlad
  Ring of Vlad at Faerie Card
  Eye of Vlad at Bat Card
  Spike Breaker at Power of Wolf
  Diamond at Gold ring
  Silver Ring at Spike Breaker
  Stone mask at Holy Symbol
Solutions:
  Stone mask < Merman Statue < Leap Stone
                               ^ Soul of Wolf < Jewel of Open < Gravity Boots
                               ^ Power of Wolf
  Heart of Vlad
  ^ Silver Ring
    ^ Soul of Bat
      ^ Form of Mist < Stone mask < Merman Statue < Leap Stone
                                                    ^ Soul of Wolf < Jewel of Open < Gravity Boots
                                                    ^ Power of Wolf
      ^ Spike Breaker < Leap Stone
                        ^ Soul of Wolf < Jewel of Open < Gravity Boots
                        ^ Power of Wolf
    ^ Echo of Bat < Leap Stone
                    ^ Soul of Wolf < Jewel of Open < Gravity Boots
                    ^ Power of Wolf
  ^ Diamond < Leap Stone
              ^ Soul of Wolf < Jewel of Open < Gravity Boots
              ^ Power of Wolf
  Tooth of Vlad < Stone mask < Merman Statue < Leap Stone
                                               ^ Soul of Wolf < Jewel of Open < Gravity Boots
                                               ^ Power of Wolf
  Rib of Vlad < Stone mask < Merman Statue < Leap Stone
                                             ^ Soul of Wolf < Jewel of Open < Gravity Boots
                                             ^ Power of Wolf
  Ring of Vlad < Gravity Boots
  Eye of Vlad < Gravity Boots
Complexity: 10

# Playthrough information

So... I've been all through both castles, and I have no silver ring or item with it's description text.

I have 196.8% map coverage, which includes all of the relic locations I can reach.  The only areas remaining are holy glasses (I have the Gold Ring description on accessory item Diamond, Silver Ring is missing) location in the regular castle and the Shaft/Dracula area in inverted castle.

I'm still missing Silver Ring (or equivalent with another name - should have been at Spike Breaker as per spoiler), Skill of Wolf (should have been at Soul of Bat as per spoiler), Cube of Zoe (should have been at Merman Statue), Ring of Vlad (should have been at Faerie Card), and Heart of Vlad (should theoretically still be at the holy glasses plot event).

It seems to me like some relics just didn't spawn.

**Comment by TalicZealot** [comment]
I checked the seed and Silver Ring was exactly where the seed says it is. Are you sure you randomized the original bin and not one that had already been randomized?

**Comment by VirtualEstatePlanner** [comment]
That's probably what happened.  I'll try another spin on the seed in a couple of hours.

**Comment by 3snowp7im** [comment]
Closing because this sounds like a classic case of a re-randomized bin. Feel free to open a new ticket if you experience similar issues with a verified vanilla bin.

**Comment by VirtualEstatePlanner** [comment]
I'm trying a run off a verified vanilla bin, and none of the item locations or drops seem different - just that some of them are there now.

Is this the behavior we expect from a double randomized seed?

If needed, I can send you the faulty bin file.

**Comment by TalicZealot** [comment]
This is expected, you should use a vanilla non-randomized bin to generate seeds.
