### ISSUE TITLE
"Disc image is not a valid or vanilla backup" on releases after 3.5.7

### ISSUE THREAD

**Issue by Rosemon** [sotnrando/sotnrando#65]
It's not recognizing my .bin file after 3.5.7, it's certainly not my rom since the CRC matches with redump's database

**Comment by 3snowp7im** [comment]
You need to check your bin again. I have confirmed that my bin is working with the latest randomizer.

```
mouse@glovesmeller:~/sotn$ crc32 sotn.bin
05be47b2
mouse@glovesmeller:~/sotn$ sha256sum sotn.bin
ce01203a9df93e001b88ef4c350889c19f11ffba89d20f214bdd8dec0b2d8d7c  sotn.bin
mouse@glovesmeller:~/sotn$ 
```
