### ISSUE TITLE
Suggestions for the FAQ section

### ISSUE THREAD

**Issue by asdheyb** [sotnrando/sotnrando#66]
Considering many users have repeatedly been asking the same questions for the last few months, I thought it would be a good idea to add these so no-one will read them and will keep asking the same questions on Discord:

- (removed to avoid spoilers)

- How can I disable music randomization?
Uncheck the Preset box and uncheck Music.

- How can I disable randomized sprites/stats?
Uncheck the Preset box and uncheck Item stats.

- Why are there missing items in my seed? Is that normal?
Yes, this is normal. There are between 1 and 3 missing items in each area of the game in order to prevent information leaks that will give the player clues whether the next progression item can be found in that area or not.

- What's the difference between Safe and Casual?
Casual shuffles items and relics among their vanilla locations, whereas Safe adds the "Guarded" extension, which includes Crystal Cloak (behind Scylla), Mormegil (behind Granfalloon), Ring of Arcana (behind Beelzebub), Fake Trio and Dark Blade (behind Doppleganger40) as potential relic/item locations.

- What's the difference between Safe and Adventure?
Safe only uses vanilla locations plus the "Guarded" extension as potential item/relic locations, whereas Adventure can have progression items in any location where a piece of equipment is found in the vanilla game. This means objects such as chestpieces, swords, shields, capes and accessories, including gems, can be a relic or progression item, but not use items, such as throwing stars, food, medicine, etc.

- What do the Classic, Guarded and Equipment options do?
You will find an explanation if you hover your cursor over the question mark next to each option.
Classic means relics and progression items will be shuffled among their vanilla locations.
Guarded introduces Crystal Cloak (behind Scylla), Mormegil (behind Granfalloon), Ring of Arcana (behind Beelzebub), Fake Trio and Dark Blade (behind Doppleganger40) as potential relic/item locations.
Equipment makes any piece of equipment a potential check.

- What is Tournament mode?
Tournament mode is the setting used for races in order to prevent players from looking at the relic locations and solutions. Information about your starting equipment can still be obtained by checking the "Show spoilers" option. Seeds with the same name but generated with or without this option checked will produce different results.

- What does the "Append seed to file name" option do?
It apends the name of your seed to the name of your bin. This means the new bin will generate with the name of your seed at the end. Bear in mind if you have selected this option, you will either need to modify your cue file so that it reads the bin with the seed name or delete the name of the seed from the bin so the cue reads it as the vanilla bin.

- Why can't I chain gravity jumps?
Gravity jumps can be chained if the player has access to a divekick. This can be achieved with Leap Stone, any transformation, or after performing a thrust sword (Claymore, Estoc, Flamberge, Zwei Hander, Obsidian sword) special attack (back, forward + attack). Otherwise, the player will only be able to perform a single gravity jump.

- (A question related to the newly added hash check for randomisation, like "Why does sotn.io reject my bin?"; I haven't got the error, so I don't know what it looks like)

I apologise if any of these answers gives wrong info, please correct me where I'm wrong.

**Comment by 3snowp7im** [comment]
I've added some of these to FAQ and added tooltips for the Append seed and Tournament mode options. Turkey mode is still not meant to be spoiled and doing so is frowned upon.
