### ISSUE TITLE
Not an issue but a discovery - soul of wolf/no leap stone/ gravity boot infinite jump

### ISSUE THREAD

**Issue by pervidefedback** [sotnrando/sotnrando#69]
I'm sure you probably already know this but I discovered that if you get the wolf soul/transform relic, you can jump, turn into the wolf, turn back to alucard, then have infinite gravity boot jump until mana runs out as usual WITHOUT getting the leap stone/double jump.

**Comment by 3snowp7im** [comment]
Yes, and? This is exactly how the original game behaves. If you have an issue with this, go back to 1997 and bring it up with Iga.

**Comment by pervidefedback** [comment]
Yeah I just realized this is mentioned in the faq.  Sorry!
