### ISSUE TITLE
Seed 1554326751863, Medusa didn't drop anything

### ISSUE THREAD

**Issue by lynxwinters** [sotnrando/sotnrando#7]
Ended up in an unwinnable state because one of the vlad relics didn't show up. My guess is that it was supposed to appear at Medusa, but when Medusa died no item appeared.

**Comment by 3snowp7im** [comment]
If you can attach a save game file (.mcr) and some information about how you played the game (which console or emulator for instance), I will try to reproduce this behavior, but without this information I'm afraid there isn't much I can do.

**Comment by 3snowp7im** [comment]
Should be fixed in https://github.com/3snowp7im/SotN-Relic-Randomizer/commit/8ddafb97b0934bf0b1ca627f82501f15e4bdfe36
