### ISSUE TITLE
Feature request: Start with full maps (both castles)

### ISSUE THREAD

**Issue by UsurperGrimm** [sotnrando/sotnrando#70]
This was something I was thinking about. Would it be possible to implement this for people brand new to SOTN or SOTN Randomizer? It can be pretty overwhelming finding some checks when you don't know the castle layout that well. The tracker is nice for giving indicators for checks but sometimes if you don't have the map filled it is hard to figure out how to get to that check. Could be implemented into safe or casual mode as a default.

**Comment by 3snowp7im** [comment]
The randomizer does not implement any features that are simply meant to improve quality of life. You should use an external tool of some kind for that. Maybe talic would implement such a thing in his tracker as an optional toggle. Also, the librarian sells castle maps that will guide you to almost every relic location, so it's hard to justify this as a separate feature when there is an in-game mechanic doing just what you're asking for.

**Comment by UsurperGrimm** [comment]
Fair enough. Never know until you try. Thanks.
