### ISSUE TITLE
Feature Request: Limited Randomization / Alternative OG Logic Preset

### ISSUE THREAD

**Issue by thecoldmage** [sotnrando/sotnrando#73]
Throwing this idea out there. After watching some recent OG preset races and remembering what made that logic work, it really comes down to the fact that you had 4 items that were always in the same static locations. I realize this was more to do with the an incomplete understanding of how the game worked at the time more so than an intentional design choice; but the way it structured the gameplay made it interesting and unique in its own way. There was always sort of 2 main objectives to a run; you had the first quest of getting Holy Glasses, and the second quest (happening in tandem of getting the Vlad Relics). 

My proposal is iterating on the logic of OG where instead of the Spike Breaker/Silver Ring/Gold Ring/Holy Glasses in their default locations, you have 4 randomly assigned items/relics in their default locations, and then the randomizer logic is run with those checks accounted for. This would be a preset identical to OG in every respect except 4 of the items/relics are not randomized. No Guarded logic, no item stat shuffle, etc. A unique feature to this type of seed is you would need to be told which of the 4 locations are in the default locations.
 
I suppose the easiest way to communicate that would be in the spoiler log on the web page at the top near the starting equipment, so other details are still out of view unless you scroll down. Another option would be, the list of predefined items/relics are revealed in a separate element on the web page, independent of the spoiler section. If run on command line it could generate the information in a text file. Alternatively, perhaps these locations could be shown on the screen where you put in your name. Not sure what’s really possible there. It does appear its already possible to place the seed name and randomizer version information there so other information might be possible? 

I would understand if the 4 checks would themselves need to be part of some predefined logical chain similar to acquiring holy glasses, like Leap Stone -> Form of Mist -> Soul of Bat -> Spike Breaker. I'll admit, there may only be handful of scenarios that would make sense, and those logical chains may need to be structured manually. Or at least any scenario that would result in a soft-lock would be omitted from consideration. For this type of logic, 4 might not even be the right number. Maybe 3 items/relics is better.

I suppose knowing where certain non-progression items/relics from the start would also have its own strategy. Like if you knew Spirit Orb, Faerie Scroll, and Faerie Card were in their default locations you would just avoid them, and make routing decisions accordingly. Although, I think in the spirit of the OG preset, the relics or items should probably belong to a logical progression chain. A case could be made for either idea.

Ultimately, the idea is to create a mix of randomized and already known locations and figuring out the best way to reach them occurring along side the grander objective of finding the Vlad relics. That is sort of the dynamic with the OG logic and it has its own merit that people seem to really enjoy.

If this is a terrible idea or not worth pursuing, I'll return back to lurking. Thank you for your time and any consideration you may have.

**Comment by eldri7ch2** [comment]
Was this taken care of with the subsequent logic changes? 2021 was a long time ago.

**Comment by thecoldmage** [comment]
Oh yeah. This was from ages ago at this point. You guys have opened the randomizer up in ways I couldn’t have possibly imagined since then. Feel free to close this.

**Comment by eldri7ch2** [comment]
Nice, thanks!
