### ISSUE TITLE
Seed "Poxa Lu" unbeatable at bat-master preset

### ISSUE THREAD

**Issue by platenyponchet** [sotnrando/sotnrando#74]
# Seed Information
Preset: bat-master
Seed: https://dev.sotn.io/?p:bat-master,f92,Poxa%20Lu

Beatable only with out of logic techs.

# Randomizer version:
3.6.0-0

# Spoilers:
Seed: Poxa Lu
Starting equipment:
  Alucard sword
  Knight shield
  Bandanna
  Ice mail
  Reverse cloak
  Duplicator
Relic locations:
  Soul of Bat at Merman Statue
  Fire of Bat at Ring of Arcana
  Echo of Bat at Form of Mist
  Force of Echo at Heart of Vlad
  Soul of Wolf at Faerie Scroll
  Power of Wolf at Fire of Bat
  Skill of Wolf at Gas Cloud
  Form of Mist at Soul of Wolf
  Power of Mist at Bat Card
  Gas Cloud at Holy Symbol
  Cube of Zoe at Soul of Bat
  Spirit Orb at Skill of Wolf
  Gravity Boots at Spike Breaker
  Leap Stone at Holy glasses
  Holy Symbol at Crystal cloak
  Faerie Scroll at Leap Stone
  Jewel of Open at Faerie Card
  Merman Statue at Sword Card
  Bat Card at Power of Wolf
  Ghost Card at Demon Card
  Faerie Card at Trio
  Demon Card at Shotel
  Sword Card at Eye of Vlad
  Sprite Card at Cube of Zoe
  Nosedevil Card at Dark Blade
  Heart of Vlad at Dragon helm
  Tooth of Vlad at Force of Echo
  Rib of Vlad at Staurolite
  Ring of Vlad at Jewel of Open
  Eye of Vlad at Ring of Vlad
  Spike Breaker at Gravity Boots
  Gold ring at Gold ring
  Silver ring at Tooth of Vlad
  Holy glasses at Spirit Orb
Solutions:
  Holy glasses
  Heart of Vlad
  ^ Soul of Bat < Jewel of Open
                  ^ Soul of Wolf
                  ^ Form of Mist
  ^ Holy glasses
  Tooth of Vlad
  ^ Soul of Bat < Jewel of Open
                  ^ Soul of Wolf
                  ^ Form of Mist
  ^ Holy glasses
  Rib of Vlad
  ^ Soul of Bat < Jewel of Open
                  ^ Soul of Wolf
                  ^ Form of Mist
  ^ Holy glasses
  Ring of Vlad
  Eye of Vlad
  ^ Soul of Bat < Jewel of Open
                  ^ Soul of Wolf
                  ^ Form of Mist
  ^ Holy glasses
Complexity: 4

# Print screen:

![WhatsApp Image 2021-12-30 at 16 57 59](https://user-images.githubusercontent.com/11446072/147784899-11be78a6-d617-4f8f-a972-2a3c02e6042a.jpeg)

**Comment by 3snowp7im** [comment]
As indicated by the tracker and defined by the preset logic, getting to faerie card location is actually in logic using Mist + Wolf: https://github.com/3snowp7im/SotN-Randomizer/blob/master/presets/bat-master.json#L149

This is how it's done in the any% route. I will add a note to the preset description that it may require limited speedrun tech.
