### ISSUE TITLE
Softlocked Seed

### ISSUE THREAD

**Issue by Rexius55** [sotnrando/sotnrando#78]
Seed: 1647390981323
Tournament Mode: No

3.7.1 adventure

Relic locations:
  Soul of Bat at Echo of Bat
  Fire of Bat at Moon rod
  Echo of Bat at Bronze cuirass
  Force of Echo at Soul of Wolf
  Soul of Wolf at Gold ring
  Power of Wolf at Ring of Ares
  Skill of Wolf at Tooth of Vlad
  Form of Mist at Badelaire
  Power of Mist at Library Onyx
  Gas Cloud at Falchion
  Cube of Zoe at Gold plate
  Spirit Orb at Gram
  Gravity Boots at Alucart sword
  Leap Stone at Jewel knuckles
  Holy Symbol at Rib of Vlad
  Faerie Scroll at Merman Statue
  Jewel of Open at Ghost Card
  Merman Statue at Walk armor
  Bat Card at Shotel
  Ghost Card at Icebrand
  Faerie Card at Gladius
  Demon Card at Sword of Dawn
  Sword Card at Trio
  Sprite Card at Jewel of Open
  Nosedevil Card at Mormegil
  Heart of Vlad at Demon Card
  Tooth of Vlad at Silver ring
  Rib of Vlad at Katana
  Ring of Vlad at Beryl circlet
  Eye of Vlad at Twilight cloak
  Spike Breaker at Force of Echo
  Onyx at Bat Card
  King's stone at Form of Mist
  Holy glasses at Spike Breaker

**As far as I was able to get through the seed with a life apple-death knockback strat to get on some higher ledges:**
![image](https://user-images.githubusercontent.com/90222204/158714916-30d9dd67-36d9-4457-be4f-8fe4d71f2821.png)

**Comment by TalicZealot** [comment]
Leap Stone at Jewel knuckles, Cube of Zoe at Gold plate, Gravity Boots at Alucart sword
Finding a stopwatch will let you progress through chaining gravity boots.
