### ISSUE TITLE
Feature Request: Power of Sire Flash Removal

### ISSUE THREAD

**Issue by MottZilla** [sotnrando/sotnrando#85]
Using the Power of Sire causes the screen to flash every 8 frames many times. This can be annoying for some but a serious problem for photosensitive people. The flashing can be removed by patching the ISO at $136580 with bytes 08 00 E0 03 00 00 00 00. Alternatively I've attached a PPF patch file.

I suggest having an option to disable the flashing so the user can choose their preference.
[CVSotN Power of Sire Flash Removal By MottZilla.zip](https://github.com/3snowp7im/SotN-Randomizer/files/9749559/CVSotN.Power.of.Sire.Flash.Removal.By.MottZilla.zip)

**Comment by TalicZealot** [comment]
I've made a pull request to address this.

**Comment by 3snowp7im** [comment]
https://github.com/3snowp7im/SotN-Randomizer/pull/86
