### ISSUE TITLE
Issue with complexity logic

### ISSUE THREAD

**Issue by Imakuni** [sotnrando/sotnrando#88]
When doing a custom seed, the logic calculates an incorrect complexity chain. The seed was generated through the following command, which is for Expedition with complexity increased to minium 8

node randomize -p expedition -s SarahSilverman -o seeds/Comp8ExpSeed1-SarahSilverman.ppf

The expected solution was Mist (1), Joo (2), Rings (3), Echo (4), Merman Statue (5), Holy Symbol (6), Demon Card (7), Final Vlad (8)

But the actual complexity chain was (1) Mist + Holy Glasses, (2) Joo + Nose Devil, (3) Final Vlad.

**Comment by TalicZealot** [comment]
Were these solutions generated and compared on the same version of the randomizer?

**Comment by 3snowp7im** [comment]
https://github.com/3snowp7im/SotN-Randomizer/pull/90
