### ISSUE TITLE
Possible Issue With Seeds Starting With Shield Rod In Inventory

### ISSUE THREAD

**Issue by Gods666thChild** [sotnrando/sotnrando#92]
---
name: Possible Issue With Seeds Starting With Shield Rod In Inventory
about: Player can cast shield spell after Death takes away Shield Rod
assignees: 3snowp7im
---
# Seed Information
I believe any seed that starts with Shield Rod.
A PPF immediately available in the #other-videos channel of The Long Library 12/23/22

# Randomizer version:
3.12.7

# Operating system and version:
Windows 10

# Emulator and version:
Bizhawk 2.8 x64

# Bug description
Player retains ability to cast shield spells after Death takes away Shield Rod from inventory, manna permitted.
Ability to do so is lost upon opening and closing the menu.

# How to reproduce:
Begin a seed with Shield Rod as starting inventory.
Let Death take your inventory. Attempt shield spell and it should cast based on two seeds I've tested.
Open the menu and close the menu and the ability to cast spells is lost.

I have not tested with Mablung Sword. And I lost my note on how to change starting inventory on vanilla bins.

**Comment by Gods666thChild** [comment]
sorry. i didnt see the issue template. will edit accordingly.

**Comment by TalicZealot** [comment]
From what I can tell this is what happens when the inventory slot gets set to 0(empty hand) without re-loading. Also yes it is the same with Mablung.

**Comment by eldri7ch2** [comment]
I'm gonna call this a feature. LMAO
