### ISSUE TITLE
New M&W Softlock Fix Causes Softlock With Axe Lord Armor

### ISSUE THREAD

**Issue by Gods666thChild** [sotnrando/sotnrando#99]
# Seed Information
Tested on Safe, Guarded OG and Lycanthrope. Suspect all presets/seeds are vulnerable.

# Randomizer version:
3.13.7 (current)

# Emulator and version:
Bizhawk 2.8 x64

# Bug description
New patch fix for Minotaur & Werewolf softlocks Axe Lord Armor upon boss fight entry from either left or right side.

# How to reproduce:
Enter fight in Axe Lord Armor either left side or right side of M&W fight.
https://www.youtube.com/watch?v=n4LwpxwyGZE

**Comment by MottZilla** [comment]
Will be addressed shortly.
Edit: Pull request addressing issue submitted.
Edit: Issue can probably be closed as it should be solved now.
